- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepositoryIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapperTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceTest.java
added the necessary columns for email and password, and the respective setter and getters
> user entity setup #24

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepository.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserPutDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepositoryIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapperTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceIntegrationTest.java
Implements Issues #30, #31, #36
REST methods for /users and /users/{id} now available for:
* POST
* GET
* PUT
* DELETE
> Enable /users REST endpoint

- contributions.md
Pull contributions.md from main branch.
> Create initial version of contributions.md

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/AuthenticationException.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/GlobalExceptionAdvice.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/UserNotFoundException.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserLoginPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserLogoutPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/repository/UserRepositoryIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceTest.java
Addressed issues #40, #41, #60 
New endpoints:
- /login 
- /logout
- /users/username/{username} to address Daniels request in #35 
UserService:
- getUserByUsername
- loginUser
- invalidateToken
> Login functionalities

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/UserController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserLogoutPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/UserControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceTest.java
Updated the logout function to include a token comparison 
Added several tests for logout and login
> #60 updated logout function and tests

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlantGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/PlantService.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceTest.java
PlantService:
- GetOwnedPlantsByUserId
- getCaretakerPlantsByUserId
Controller:
- Respective Endpoints
> #47 and #48 getting plants for userId (Owner + careTaker) and respective controller methods

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Plant.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlantGetDTO.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
> [#46] Add REST controllers for plant

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/SpaceGetDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/SpacePostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/SpacePutDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapper.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/rest/mapper/DTOMapperTest.java
> [#84] Add REST endpoints to spaces.

- src/main/java/ch/uzh/ifi/hase/soprafs24/config/DatabaseLoader.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/EmailMessageDTO.java
* Switched sender domain from @uzh.ch to @plantparent.ch after confirming SPF and DKIM via DNS records
* New sender is groot-root@plantparent.ch
* Switched initial users email address to *@muell.icu so they are sent to an actual mailbox.
* You can see the mails here: https://muellmail.com/en#/initialuser@muell.icu
* Add a new replyTo with my email address in case someones mail gets put into the app and they really need to reach someone. We don't want to get abused by spammers.
* Turned off sandbox mode. Now mails get actually sent out.
Closes #123
> 123 fix emails land in quarantine

- src/main/java/ch/uzh/ifi/hase/soprafs24/config/DatabaseLoader.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Plant.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Space.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/GlobalExceptionAdvice.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/SpaceNotFoundException.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/SpaceAssignmentPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/PlantService.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpaceService.java
- src/main/resources/application.properties
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceTest.java
* Added spaces dummy data
* Adjusted the relation between spaces and plant so that the plantsContained list gets correctly populated
* implemented an endpoint and service function to retrieve all plants within a space
** A call to this endpoint returns a list of plants which also contains a reference to the space it is in, this may be unnecessary information, might create a new DTO for this, if this is a problem
> Get all plants for space

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/GlobalExceptionAdvice.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/SpaceNotFoundException.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/SpaceAssignmentPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/PlantService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/PlantServiceTest.java
Added the service layer methods in the PlantService to add/ remove a plant to/from a space
> #87 space assignment/removal -> service layer

- src/main/java/ch/uzh/ifi/hase/soprafs24/utility/DataBucketUtility.java
GAE is read only except for /tmp directory
close #139
> [#139] Move upload directory to /tmp

- src/main/java/ch/uzh/ifi/hase/soprafs24/config/DatabaseLoader.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/PlantController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Space.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/MemberPostDTO.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/PlantService.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpaceService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceTest.java
* Added the relation between users (as members) and spaces.
* Methods to add/remove users to/from spaces, service and controller
** I noticed that when doing a GET request for a user, the spaces owned list contains duplicates (same issue as we had with plants). I tried to solve this by again adjusting the FetchType but this led to broader issues. Will have to address this later, just keep in mind.
> Space membership

- src/main/resources/application-gcp.properties
- src/main/resources/bootstrap.properties
I became insane, with long intervals of horrible sanity. - Edgar Allan Poe
> [#143] Put "unneeded" config back in

- build.gradle
- src/main/resources/application-gcp.properties
https://codelabs.developers.google.com/codelabs/cloud-spring-petclinic-cloudsql#4
> [#143] Change config according to codelabs

- build.gradle
- src/main/resources/application-gcp.properties
maybe gcp will now recognise this...
> [#143] Add more jdbc and mysql dependencies... 

- src/main/java/ch/uzh/ifi/hase/soprafs24/config/DatabaseLoader.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
Changed the DB-Loader to rely on service methods
> Refactor db loader

- .github/workflows/main.yml
- build.gradle
- src/main/java/ch/uzh/ifi/hase/soprafs24/config/DatabaseLoader.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
- src/main/resources/application-gcp.properties
This implementation also utilizes postgres-socket-factory to connect. The column for the User entity needed to be renamed because user is a protected keyword.
> [#143] Change DB configuration to PostgreSQL

- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/PlantControllerTest.java
added missing controller tests. Now every endpoint should have at least one test
> added missing Plant Controller tests

- src/main/java/ch/uzh/ifi/hase/soprafs24/utility/DataBucketUtility.java
by checking path like their example
> [#178] Fix SonarCloud quality gate requirements

- src/main/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceController.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/exceptions/SpaceAlreadyExistsException.java
- src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpaceService.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/controller/SpaceControllerTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceIntegrationTest.java
- src/test/java/ch/uzh/ifi/hase/soprafs24/service/SpaceServiceTest.java
- Added service methods to add/remove plants to/from spaces
- Added controller methods to add/remove plants to/from spaces
- Fixed delete method in service: deleted space is removed from plants as well
- Fixed a type & removed unused imports
> Spaces add plant

- src/main/java/ch/uzh/ifi/hase/soprafs24/utility/DataBucketUtility.java
> [#195] Add allowed file types to exception message

- src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpaceService.java
* Updated the checks in the addPlantToSpace function so they properly work (also updated the same checks in the deletePlantFromSpace() method)
* This fixed the issue when i tested it
> #200 owner as caretaker bug fix
